const productsData = [
    {
        id: 1,
        // img: "",
        description: "description: ",
        rating: "★★★★",
        title: "This is a test",
        price: 54500,
        quantity: 1,
    },
    {
        id: 2,
        // img: "",
        description: "description: ",
        rating: "★★★★★",
        title: "test2",
        price: 31000,
        quantity: 1,
    },
    {
        id: 3,
        // img: "",
        description: "description: ",
        rating: "★★★★",
        title: "test3",
        price: 84007,
        quantity: 1,
    },
    {
        id: 4,
        // img: "",
        description: "description: ",
        rating: "★★★★★",
        title: "test4",
        price: 53570,
        quantity: 1,
    },
    {
        id: 5,
        // img: "",
        description: "description: ",
        rating: "★★★★",
        title: "test5",
        price: 147990,
        quantity: 1,
    },
    {
        id: 6,
        // img: "",
        description: "description: ",
        rating: "★★★★★",
        title: "test6",
        price: 54500,
        quantity: 1,
    },
    {
        id: 7,
        // img: "",
        description: "description: ",
        rating: "★★★★",
        title: "test7",
        price: 24990,
        quantity: 1,
    },
    {
        id: 8,
        // img: "",
        description: "description: ",
        rating: "★★★★",
        title: "test8",
        price: 54500,
        quantity: 1,
    }
];

export default productsData;